# Creating a job which will run a container which sleeps for 3 seconds and stops
# $ kubectl create job
# $ kubectl describe job.batch sleepy

apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec: 
  template:
    spec: 
      containers: 
      - name: resting
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
