# Creating a job which will run a container which sleeps for 3 seconds and stops
# Adding backoffLimit, Completions and Parsllelism to see the changes to the job

# $ kubectl create job
# $ kubectl describe job.batch sleepy

apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec: 
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 15
  template:
    spec: 
      containers: 
      - name: resting
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
