apiVersion: v1
kind: Pod
metadata:
  name: secondapp
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: busy
      image: busybox
      command:
        - sleep
        - "3600"
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]

# kubectl create -f second.yaml
# kubectl exec -it secondapp -- sh
# $ ps aux
# $ grep Cap /proc/1/status
# use the capability shell wrapper tool, the capsh command to decode the output
# capsh --decode=00000000a80425fb