apiVersion: v1
kind: Pod
metadata:
  name: secondapp
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: busy
      image: busybox
      command:
        - sleep
        - "3600"
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false

# kubectl create -f second.yaml
# kubectl exec -it secondapp -- sh
# $ ps aux
# 4grep Cap /proc/1/status
